### ISSUE TITLE
Table numbers not incrementing beyond 2

### ISSUE THREAD

**Issue by nealkruis** [tomduck/pandoc-tablenos#1]
pandoc 1.17.02
## Markdown input:

```
A B
- -
0 1

Table: Even simpler. {#tbl:}

A B
- -
0 1

Table: Even simpler. {#tbl:}

A B
- -
0 1

Table: Even simpler. {#tbl:}

A B
- -
0 1

Table: Even simpler. {#tbl:}
```
## HTML output:

<a name="tbl:"></a>

<table>
<caption>Table 1. Even simpler. </caption>
<thead>
<tr class="header">
<th align="left">A</th>
<th align="left">B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="left">1</td>
</tr>
</tbody>
</table>

<a name="tbl:"></a>

<table>
<caption>Table 2. Even simpler. </caption>
<thead>
<tr class="header">
<th align="left">A</th>
<th align="left">B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="left">1</td>
</tr>
</tbody>
</table>

<a name="tbl:"></a>

<table>
<caption>Table 2. Even simpler. </caption>
<thead>
<tr class="header">
<th align="left">A</th>
<th align="left">B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="left">1</td>
</tr>
</tbody>
</table>

<a name="tbl:"></a>

<table>
<caption>Table 2. Even simpler. </caption>
<thead>
<tr class="header">
<th align="left">A</th>
<th align="left">B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="left">1</td>
</tr>
</tbody>
</table>

**Comment by nealkruis** [comment]
This seems to happen only for tables without defined IDs. The first and second instances are incremented correctly, but any consecutive tables without IDs share the same number as the second.

A work around is to add a dummy ID to every other table.

**Comment by tomduck** [comment]
Thank you both for the feedback.  I am getting the same result for id-less tables under html, and am working on a fix.

**Comment by tomduck** [comment]
I have posted the fixed code to GitHub.  Could either of you test it out and let me know if the fix works for you?  Thanks in advance.

**Comment by nealkruis** [comment]
It works for the case I illustrated above!

**Comment by tomduck** [comment]
Splendid.  Thank you both for your feedback.  I'm doing some refactoring to support fancy new features.  I will push out the changes together when they are ready, and will post a notice here.  Stay tuned...

**Comment by tomduck** [comment]
I just posted a new release to pypi with this fix.  Please let me know if you have any trouble with it.  Cheers!
