### ISSUE TITLE
Why is id in link before table instead of on table itself

### ISSUE THREAD

**Issue by vincerubinetti** [tomduck/pandoc-tablenos#11]
The output of `tablenos` seems to put the id/anchor to the table in a `<a>` tag preceding the table instead of in the `<table>` element itself. I was wondering what the reason is for that, and if there's a way to configure the plugin to remedy that.

I get output that resembles this:

```html
<a name="tbl:bowling-scores"></a>
<table>
<caption><span>Table 1:</span> Bowling scores</caption>
<thead>
<tr class="header">
...
</tr>
</thead>
<tbody>
<tr class="odd">
...
</tr>
<tr class="even">
...
</tr>
<tr class="odd">
...
</tr>
</tbody>
</table>
```

**Comment by tomduck** [comment]
Hi, Vincent.

After looking into it, we have a similar problem here to what we found with [figure ids in pandoc-fignos](https://github.com/tomduck/pandoc-fignos/issues/65).  Pandoc's table type is currently unattributed, so there is no way for me to pass id information on to pandoc.  My workaround was to place an anchor immediately before the table.

Cheers,
Tom

**Comment by tomduck** [comment]
I'm going to close this because it follows our earlier exchange, but please feel welcome to reopen it if there is more discussion to be had.  --Tom
