### ISSUE TITLE
Duplicate table numbers in HTML without section numbering

### ISSUE THREAD

**Issue by timtroendle** [tomduck/pandoc-tablenos#17]
Without section numbering, table numbers in HTML restart in each section nevertheless.

Here is an example:
```
# First section

[table def here]

# Second section

[table def here]
```

This leads to both tables having number 1.

**Comment by timtroendle** [comment]
The same issue and the same fix exists for fignos:

https://github.com/tomduck/pandoc-fignos/issues/76

**Comment by tomduck** [comment]
Thank you for this report and sorry for the long wait.  The problem is now fixed in the `nextrelease` branch.  If the problem reappears after the next release, please feel welcome to re-open this issue.

Tom
