### ISSUE TITLE
table caption without identifier

### ISSUE THREAD

**Issue by nononame** [tomduck/pandoc-tablenos#2]
I have a bug at [line 293](https://github.com/tomduck/pandoc-tablenos/blob/46254c17c221493a3fbbf75d073c857043b61e10/pandoc_tablenos.py#L293)

The program reads  `attrs.id` but if not identifier was write for this table in the markdown source, this field does not exist and an exception stop the program.

Simon.

**Comment by tomduck** [comment]
Ooh!  Good catch.  I have posted the fixed code to GitHub.  Would you mind testing it and letting me know it works for you?

**Comment by nononame** [comment]
Perfect. It works now, Thanks for your tool !

**Comment by tomduck** [comment]
A new version with this fix is now posted to pypi.  Thanks for your feedback, and please let me know if you have any trouble with it.  Cheers!
