### ISSUE TITLE
Allow arbitrary text as table number

### ISSUE THREAD

**Issue by davidanthoff** [tomduck/pandoc-tablenos#3]
This would be the equivalent to tomduck/pandoc-eqnos#9, for example

```
Table: Some title {#tbl:A tag="A"}
```

would view as

```
Table A: Some title
```

**Comment by tomduck** [comment]
Agreed, this would be nice to have.  I'm working on another Issue right now for all three packages (clever referencing), and will queue this one up.  Thanks for the suggestion.  :o)

**Comment by tomduck** [comment]
I have this working in the 'tagged' branch.  If it works for you, then I will prepare a new release some time this week.

**Comment by tomduck** [comment]
Note that I also have this ready to go for pandoc-fignos.

**Comment by davidanthoff** [comment]
I just tried it, and it looks good and seems to work for my case. Thanks so much!

**Comment by tomduck** [comment]
Splendid.  I just posted new versions of tablenos and fignos to pypi.

Thanks again for your feedback.  Cheers!
