### ISSUE TITLE
docx output: extra blank line before table

### ISSUE THREAD

**Issue by kugelblitz** [tomduck/pandoc-tablenos#6]
Hello,

The docx output basically works, though the three docx output files for examples stored in the repo give a false impression that it does not. 

That said, I have a serious problem using pandoc-tablenos with docx output: the filter adds an extra blank line before each table's caption. There is no extra blank line if I skip applying the filter. I do not understand the cause and found no way to work that around, can you help me?

Best regards,

Dmitry

**Comment by jrennstich** [comment]
I have the same issue.

**Comment by tomduck** [comment]
I'm restarting work on docx support for the pandoc-fignos/eqnos/tablenos filters.  I'm hoping to do either pandoc-fignos or pandoc-eqnos first.  See:

  * [pandoc-fignos Issue #34](https://github.com/tomduck/pandoc-fignos/issues/34)
  * [pandoc-eqnos Issue #29](https://github.com/tomduck/pandoc-eqnos/issues/29)

and corresponding wikis to organize materials at:

  * https://github.com/tomduck/pandoc-fignos/wiki/Development#docx-output
  * https://github.com/tomduck/pandoc-eqnos/wiki/Development#docx-output

Once those two have been solved, moving on to solve the same problem in pandoc-tablenos should be pretty straight-forward.

**Comment by landlord11** [comment]
Hi, I ran into this problem with pandoc-fignos, and making this change to the code removed the blank line:

    @@ -258,10 +258,10 @@
                 # As per http://officeopenxml.com/WPhyperlink.php
                 bookmarkstart = \
                   RawBlock('openxml',
    -                       '<w:p><w:bookmarkStart w:id="0" w:name="%s"/><w:r><w:t>'
    +                       '<w:bookmarkStart w:id="0" w:name="%s"/>'
                            %attrs[0])
                 bookmarkend = \
    -              RawBlock('openxml', '</w:t></w:r><w:bookmarkEnd w:id="0"/></w:p>')
    +              RawBlock('openxml', '<w:bookmarkEnd w:id="0"/>')
                 return [bookmarkstart, Para(value), bookmarkend]

I assume something similar is being done in tablenos, too.  Hope this helps.

Brian

**Comment by tomduck** [comment]
Thank you all for this bug report, and @landlord11 for the working code.  I have implemented it as above in the `nextrelease` branch of both pandoc-fignos and pandoc-tablenos, and will ship new versions to pipy in the next few days.  Please let me know if anything breaks: I am not a docx user.

Cheers,
Tom

**Comment by tomduck** [comment]
I'm closing this in anticipation of a new release today.
