### ISSUE TITLE
Feature request: Custom Separator

### ISSUE THREAD

**Issue by mitchpaulus** [tomduck/pandoc-tablenos#8]
Is it possible to change the separator from a colon to something else? If it is, it wasn't clear from the README. 

A new variable could be `tablenos-sep` and take an arbitrary string.

Thanks!

**Comment by tomduck** [comment]
At long last we have this -- sorry for the long wait.  Custom separators are implemented in the pandoc-tablenos 2.0.0 beta release.  To install it, use

    pip install pandoc-tablenos --user --upgrade --pre

Be sure to read the [2.0.0 documentation](https://github.com/tomduck/pandoc-tablenos/tree/2.0) first to see what has changed.

In your markdown metadata, use

    tablenos-caption-separator: period

to change the separator to a period.  Only `none`, `colon`, `period`, `space`, `quad`, and `newline` are allowed, given that these are the options supported by the LaTeX `caption` package.  Changing the separator is supported for all of the output formats, of course.

Cheers,
Tom

**Comment by tomduck** [comment]
I'm going to lose this Issue as I am trying to clean things up before the 2.0 release.  Please re-open if the Issue persists.  Thanks again for the feedback.
